### PR TITLE
Enhancement - Options to allow key value array

### PR DESCRIPTION
**Pull request by syedsalehinipg**
## Changes

- Implemented functionality to support options arrays consisting of key-value pairs

## Dependencies

N/A

## Testing notes

Example:

`[
      { key: "option-a", value: "Option A" },
      { key: "option-b", value: "Option B" }
    ]`

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [x] Lint and test workflows pass.

### CODE REVIEW

**Comment by dmbarry86** [comment]
@syedsalehinipg maybe Nikitha didn't mention during the handover, but the strategy we have RUI TypeScript migration is that all new components should be written in TypeScript and existing components get migrated when they are touched so that eventually we move everything over bit by bit.

Also, where are you planning to use this Select component? In general we should be moving to the Autocomplete.

**Comment by dmbarry86** [comment]
I would also expect some updated tests to cater for this new syntax as well as ensuring the old syntax hasn't been broken.

**Review by dmbarry86 — CHANGES_REQUESTED** [review]
- Migrate to TypeScript
- Missing tests for new behaviour
- Question over Select usage vs Autocomplete

**Comment by syedsalehinipg** [comment]
> @syedsalehinipg maybe Nikitha didn't mention during the handover, but the strategy we have with RUI TypeScript migration is that all new components should be written in TypeScript and existing components get migrated when they are touched so that eventually we move everything over bit by bit.
> 
> Also, where are you planning to use this Select component? In general we should be moving to the Autocomplete.

This was going to be for the Measures dropdown in the Unit Conversion. And regarding changing it to typescript I did think that was the idea but it's just the timeframe I planned to complete this in could be delayed if I get side tracked with changing components to typescript if I have to make any small change, hence why I didn't. But if you are okay if I don't meet what's planned then I am okay doing that.

**Comment by syedsalehinipg** [comment]
> @syedsalehinipg maybe Nikitha didn't mention during the handover, but the strategy we have with RUI TypeScript migration is that all new components should be written in TypeScript and existing components get migrated when they are touched so that eventually we move everything over bit by bit.
> 
> Also, where are you planning to use this Select component? In general we should be moving to the Autocomplete.

Should I be using the autocomplete instead? For the unit conversions I think its easier to have dropdown for a user point of view, no? 

If so I can scrap this.

**Comment by dmbarry86** [comment]
> I think its easier to have dropdown for a user point of view, no?

The autocomplete is a dropdown but is also allows to search, thus a much improved UX over Select. Run Storybook and give the Autocomplete component a try.

**Comment by syedsalehinipg** [comment]
> > I think its easier to have dropdown for a user point of view, no?
> 
> The autocomplete is a dropdown but is also allows to search, thus a much improved UX over Select. Run Storybook and give the Autocomplete component a try.

Oh yes, I see it. It is better for sure. I might have to make the same changes here too if it doesn't support key value pair options.

**Review by dmbarry86 — APPROVED** [review]

**Pull request merged**
