### PR TITLE
Enhancement - TreeViewList improvements

### PR DESCRIPTION
**Pull request by syedsalehinipg**
### This PR has the following changes:
 
- **TreeViewList**
  - Sticky Search Bar: Implemented a fix that ensures the `SearchBar` remains fixed at the top when scrolling through the list. This enhances usability by keeping the search functionality accessible.
  - Search Functionality: Resolved an issue where nodes matching the search criteria were not expanding.
  - Height Prop: Added a height prop to `TreeViewListProps`, offering more control over the component's height. 
  - onNodeToggle Prop: Modified the `onNodeToggle` prop to be optional, increasing the component's flexibility for use cases where toggle functionality is not required.
  - Toggle Callback: Addressed a missing callback issue by adding the `onNodeToggle` callback upon node toggle actions.
  - Theme Compatibility: Enhanced theme support by integrating theme colors, particularly improving the appearance in dark mode.
  
- **SearchBar** 
  - Width Prop: Introduced a new optional `width` prop to allow custom width, enhancing the component's flexibility in various layout contexts.

## UI/UX

_On scroll - the search box remains fixed to top:_
image

_Able to expand nodes after a search:_
image

_Dark mode:_
image

_Component in use (Parameter)_

Set with custom height:
image
UI:
image

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [ ] Appropriate tests have been added.
- [x] Lint and test workflows pass.

### CODE REVIEW

**Review by m4manjesh — CHANGES_REQUESTED** [review]
Funcitonality looks good. Few minor things to address

1. I would expect to see only the tree view ss scrollabe like in devel now. Fix search bar spacing issues
Screenshot (374)
2. By default component height is 90vh, this leads to more white space. Should this component takes and grow with the height of parent div in each apps or is this what we agreed somewhere?
Screenshot (375)

**Comment by syedsalehinipg** [comment]
Changes:

- Scroll bar now shows below the searchbar
- Changed the width set on stories for visual improvements
- Changed default height to 80vh 
- Added padding to outer Box
- Removed width props usage on SearchBar - no longer needed
- Added maxHeight calculation for the Tree, this allows us to add padding to the bottom where the Tree ends

_Screenshots have been updated to reflect the changes._

Regarding the height, it was discussed previously with @Sowbhagya-ipg that we wanted to use up the unused space below the Admin controls, by expanding the height of the Tree. The height prop will allow us to pass in the required height based on use case.

image

**Comment by dmbarry86** [comment]
Why are we needing to control the height from the parent? Why can't the component itself just effectively use 100% to take up all parent space?

**Review by m4manjesh — CHANGES_REQUESTED** [review]
Looks good. I agree with Dave's comment, it should be 100% be default. please address this and then we are good to go.

**Comment by syedsalehinipg** [comment]
Changed the` height` prop to optional, set the default to `100%` to match the `width` prop. This also gives us the control in storybook too, we can use the prop to set a height and see the scroll bar working too.

**Review by m4manjesh — APPROVED** [review]
LGTM

**Pull request merged**
