### PR TITLE
TD-3234 Update `RoadPreview` Component

### PR DESCRIPTION
**Pull request by AronPetrauskas**
Closes [TD-3234](https://sce.myjetbrains.com/youtrack/issue/TD-3234)
Contributes [TD-3196](https://sce.myjetbrains.com/youtrack/issue/TD-3196)

## Changes

A brief description of what this pull request solves / introduces.

- Move the `RoadPreview` component to its own
- Implement the `FormatLabel`, `FormatVersionLabel`, `FileLabel`, `DateLabel`, `UserLabel` components.
- Bound the above mentioned components in boxes, so that they truncate and size to their content properly
- Adjusted types to fit the new definitions
- Adjusted the stories to pass the props in the correct way due to the type change
- Adjusted tests to test with the new `data-testid`s

Maybe a short description of what is not included and will come in future work where appropriate.

## UI/UX

image

## Testing notes

1. Open storybook
2. Check the `RoadPreview` component
3. Make sure the `RoadPreview` component belongs to the `Preview` group in storybook
4. Make sure the component matches [FIGMA](https://www.figma.com/design/WoHtIQKM6eLlOUuzK1zlpB/VIRTO.TEST?node-id=3639-22237&node-type=instance&t=zBvJEPPmn4tRgOqi-0)
5. Make sure that you can adjust the `createdAt`, `file`, `format`, `formatVersion`, `user` values. Make sure that when these values are long truncation happens and nothing exceeds the parent component (the card).

## Author checklist

Before I request a review:

- [x] I have reviewed my own code-diff.
- [x] I have tested the changes in Docker / a deploy-preview.
- [x] I have assigned the PR to myself or an appropriate delegate.
- [x] I have added the relevant labels to the PR.
- [x] I have included appropriate tests.
- [x] I have checked that the Lint and Test workflows pass on Github.
~- [ ] I have populated the deploy-preview with relevant test data.~
- [x] I have tagged a UI/UX designer for review if this PR includes UI/UX changes.

### CODE REVIEW

**Comment by AronPetrauskas** [comment]
@Sowbhagya-ipg Can you please confirm that this component matches your expectation. Thanks!

**Comment by Sowbhagya-ipg** [comment]
Checked it looks fine for me. @AronPetrauskas

**Comment by AronPetrauskas** [comment]
@Sowbhagya-ipg The gap has been decreased and the tool tips removed. Can you please confirm everything is working well?

**Comment by AronPetrauskas** [comment]
@IvanLazarov-TVM Could you give me a re-review as a few things have changed since this PR was approved. Changes:
- Fixed DateIconLabel not being centered to UserIconLabel
- Created a non hook version of the colorMap function
- Wrote tests for both the hook version and the function of colorMap
- Fixed some export syntax

**Review by IvanLazarov-TVM — APPROVED** [review]
Looks good to me.

**Comment by AronPetrauskas** [comment]
One thing has changed, the anchor tag was longer(wider) than the text of the road name, this was fixed.

**Review by IvanLazarov-TVM — APPROVED** [review]
LGTM

**Pull request merged**
