### PR TITLE
Card component fixes

### PR DESCRIPTION
**Pull request by nikitharani**
Closes [TD-1258](https://sce.myjetbrains.com/youtrack/issue/TD-1258/Updates-for-Card-Components-in-React-ui)

Figma: 
https://www.figma.com/proto/0CVK945S1cs1ku0sUXcgv7/VIRTO.SCENE?node-id=820-43226&scaling=scale-down&page-id=0%3A1&starting-point-node-id=623%3A34220&show-proto-sidebar=1

Few fixes in the Detail Card
- removed the fixed height of the card. The header stays fixed and the File column and Detail column scroll together. 
- Fixed padding for table card stack inside detail card
- Added Spacing and adjusted height when there are no labels

DetailCardStorybook

Preview After Integrating into MM
image

Preview After Integrating into SM 
SM

### CODE REVIEW

**Comment by nikitharani** [comment]
@Sowbhagya-ipg could you please have a quick look at the screenshots I have attached above?

**Comment by Sowbhagya-ipg** [comment]
> @Sowbhagya-ipg could you please have a quick look at the screenshots I have attached above?

1. The button text should be "Download All Files"
2. There should be spacing on the top of the scroll (just below the label and the cards)
3. When there is no label selected, adjust the height accordingly.

**Comment by nikitharani** [comment]
> > @Sowbhagya-ipg could you please have a quick look at the screenshots I have attached above?
> 
> 1. The button text should be "Download All Files"
> 2. There should be spacing on the top of the scroll (just below the label and the cards)
> 3. When there is no label selected, adjust the height accordingly.

Thanks 

updated Button text 
MM Preview 
image
SM Preview
SM

Added Spacing and adjusted height when there are no labels
react-ui

**Comment by Sowbhagya-ipg** [comment]
> > > @Sowbhagya-ipg could you please have a quick look at the screenshots I have attached above?
> > 
> > 
> > 
> > 1. The button text should be "Download All Files"
> > 2. There should be spacing on the top of the scroll (just below the label and the cards)
> > 3. When there is no label selected, adjust the height accordingly.
> 
> Thanks
> 
> updated Button text
> 
> MM Preview Before image
> 
> After image
> 
> SM Preview Before SM [ SM ](https://user-images.githubusercontent.com/49191249/232476323-f00b6ff2-54e3-45f6-9c94-2cdd85de477e.gif) [ ](https://user-images.githubusercontent.com/49191249/232476323-f00b6ff2-54e3-45f6-9c94-2cdd85de477e.gif)
> 
> After sm [ sm ](https://user-images.githubusercontent.com/49191249/232723369-9b3d0b9d-1975-4040-b32e-1d7852413ba4.gif) [ ](https://user-images.githubusercontent.com/49191249/232723369-9b3d0b9d-1975-4040-b32e-1d7852413ba4.gif)
> 
> Added Spacing and adjusted height when there are no labels react-ui [ react-ui ](https://user-images.githubusercontent.com/49191249/232719344-6815905a-14c8-480d-a450-11c51d8d80c4.gif) [ ](https://user-images.githubusercontent.com/49191249/232719344-6815905a-14c8-480d-a450-11c51d8d80c4.gif)

Looks Good

**Comment by mattcorner** [comment]
Where is the scrollbar in the app integrations? I see it in the storybook recordings, but I don't see where it is in the app recordings.

**Comment by mattcorner** [comment]
In the app integration recordings, whats with the blank space at the bottom cutting off the content? 
image

I would only expect to see the bottom margin when I've scrolled to the bottom of the content. Otherwise I would expect the content to cut-off at the bottom the screen.

**Comment by m4manjesh** [comment]
@Sowbhagya-ipg @nikitharani I am a bit confused about the text in the file download button. In this ticket https://sce.myjetbrains.com/youtrack/issue/TD-1326/Download-all-only-downloads-Road-TestRun,  we have decided to change the text to 'Download Project' to avoid confusion. Please confirm which one is the correct one.

**Comment by nikitharani** [comment]
> 

The download button text in SM should be  Download Project and in MM it is Download All files

**Comment by nikitharani** [comment]
> @Sowbhagya-ipg @nikitharani I am a bit confused about the text in the file download button. In this ticket https://sce.myjetbrains.com/youtrack/issue/TD-1326/Download-all-only-downloads-Road-TestRun, we have decided to change the text to 'Download Project' to avoid confusion. Please confirm which one is the correct one.

The Download Button text in SM should be "Download Project" and in MM it is "Download All Files"

**Comment by Sowbhagya-ipg** [comment]
> In the app integration recordings, whats with the blank space at the bottom cutting off the content?
> 
> image
> 
> I would only expect to see the bottom margin when I've scrolled to the bottom of the content. Otherwise I would expect the content to cut-off at the bottom the screen.
> 
> I mention this because I think you'll need to remove the bottom padding in the app, and expose some way to add it to this component in react-ui as you want the bottom margin to be within the scroll area in this instance.
> 
> Thoughts @Sowbhagya-ipg?

@nikitharani @mattcorner My bad! I was only looking at the storybook implementation. Please update 
1. The delete icon positioning
2. The spacing in the bottom 
3. Missing Scroll
4. Missing Edit Button
5. The padding around the image should be 16px. Please check and update if it's wrong

**Review by m4manjesh — COMMENTED** [review]
@nikitharani Please fix the changes suggested by Matt and Soubhgya and let me know.

**Comment by nikitharani** [comment]
> > In the app integration recordings, whats with the blank space at the bottom cutting off the content?
> > image
> > I would only expect to see the bottom margin when I've scrolled to the bottom of the content. Otherwise I would expect the content to cut-off at the bottom the screen.
> > I mention this because I think you'll need to remove the bottom padding in the app, and expose some way to add it to this component in react-ui as you want the bottom margin to be within the scroll area in this instance.
> > Thoughts @Sowbhagya-ipg?
> 
> @nikitharani @mattcorner My bad! I was only looking at the storybook implementation. Please update
> 
> 1. The delete icon positioning
> 2. The spacing in the bottom
> 3. Missing Scroll
> 4. Missing Edit Button
> 5. The padding around the image should be 16px. Please check and update if it's wrong

Fixed delete Icon positioning, space in the bottom, and missing scroll. IN SM we don't have edit functionality yet so removed the Edit button in SM as of now. Also, the padding around the image is 16px.

**Comment by nikitharani** [comment]
Fixed suggested changes by @mattcorner and @Sowbhagya-ipg 

SM after integration of DetailCard component 
sm

**Review by m4manjesh — APPROVED** [review]
LGTM. I will leave to you to merge and release.

**Pull request merged**
