### PR TITLE
Update storybook stories to update dynamic values

### PR DESCRIPTION
**Pull request by jegasriskantha**
Updated the following  Storybook stories to ensure that the controls work as expected in storybook: 

- SwitchField
- Snackbar
- Select
- PasswordChangeDialog

### CODE REVIEW

**Comment by dmbarry86** [comment]
Changing the value control for Select component doesn't seem to have any effect. Would expect the value to be the selected item.

**Comment by dmbarry86** [comment]
PasswordChangeDialog looks good

**Comment by dmbarry86** [comment]
The open control for Snackbar doesn't seem to have any effect in any of the 3 stories. Other controls for Snackbar seem fine.

**Comment by dmbarry86** [comment]
SwitchField looks good

**Review by dmbarry86 — CHANGES_REQUESTED** [review]
Select and Snackbar components still not quite right. See comments thread.

**Comment by jegasriskantha** [comment]
> The open control for Snackbar doesn't seem to have any effect in any of the 3 stories. Other controls for Snackbar seem fine.

Fixed this now. I also changed the default for each of the stories so that the snack bar is closed initially.

**Comment by jegasriskantha** [comment]
> Changing the value control for Select component doesn't seem to have any effect. Would expect the value to be the selected item.

I think this works as expected. Would you expect not to have to enter the value within quotations in Storybook? 

Select value control

**Comment by dmbarry86** [comment]
> > Changing the value control for Select component doesn't seem to have any effect. Would expect the value to be the selected item.
> 
> I think this works as expected. Would you expect not to have to enter the value within quotations in Storybook?
> 
> Select value control

I don't think I would expect quotes. The options prop doesn't include quotes so I would kind of expect to pass in a corresponding value to select one of them.

**Comment by dmbarry86** [comment]
Same with all of the other string realted props actually, none of them include quotes.

image

**Review by dmbarry86 — CHANGES_REQUESTED** [review]
Snackbar is good now. Select still not consistent.

**Comment by jegasriskantha** [comment]
> Snackbar is good now. Select still not consistent.

Fixed. Updated the propType for Storybook so it now knows to treat "value" as a string. 
Select value control fixed

**Review by dmbarry86 — APPROVED** [review]

**Pull request merged**
