### PR TITLE
TD-2886: Tab panel background now fills whole panel

### PR DESCRIPTION
**Pull request by Skoob1905**
Closes [TD-2886](https://sce.myjetbrains.com/youtrack/issue/TD-2886/Background-colour-tab-panel-issue)
## Changes

Adds a background to the whole tab panel

## Description

Before, a background had been given to only the tab headers but not to the content, this has now been fixed

## Dependencies

N/A

## UI/UX
To prove the point, I've rendered a 500px height content with no children and a gray background. As you can see, the entire background is filled even with no children. I will be changing this back to "background.paper" in the code, as this is the actual colour we want but is impossible to see.
image

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

### CODE REVIEW

**Comment by dmbarry86** [comment]
Are you sure every instance of this component in every app will want the paper background color for tab children? Have you confirmed this with @Sowbhagya-ipg?

**Comment by dmbarry86** [comment]
👀 👀

image

**Comment by dmbarry86** [comment]
All RUI PRs should be destined for appropriate release branch, not main. Please liaise with @lukemojo.

image

**Comment by Skoob1905** [comment]
No I haven't checked this with sowbhagya, but I thought since we are using paper background to fill the content, this was a logical assumption to make ... @Sowbhagya-ipg what do you think about [this](https://github.com/IPG-Automotive-UK/react-ui/pull/912#issuecomment-2230403672)

**Comment by dmbarry86** [comment]
> No I haven't checked this with sowbhagya, but I thought since we are using paper background to fill the content, this was a logical assumption to make ... @Sowbhagya-ipg what do you think about [this](https://github.com/IPG-Automotive-UK/react-ui/pull/912#issuecomment-2230403672)

Don't just consider SCENE, consider all apps that might want to use it.

Also I recommend a pre-release and integrating it into VIRTO as part of this PR to check it acutally addresses the specific SCENE issue.

**Comment by Skoob1905** [comment]
> > No I haven't checked this with sowbhagya, but I thought since we are using paper background to fill the content, this was a logical assumption to make ... @Sowbhagya-ipg what do you think about [this](https://github.com/IPG-Automotive-UK/react-ui/pull/912#issuecomment-2230403672)
> 
> Don't just consider SCENE, consider all apps that might want to use it.
> 
> Also I recommend a pre-release and integrating it into VIRTO as part of this PR to check it acutally addresses the specific SCENE issue.

Makes sense to me

**Comment by dmbarry86** [comment]
Discussed this with @Skoob1905 on chat and agreed the correct fix here is to update the parent box for the curently active tab to have full height. No need to change any existing backgrounds as this is already styled correctly once the height is full. He will make the chnages.

**Comment by Skoob1905** [comment]
This has now been based from a release branch for 8.1.1, when we get this merged we can create a pre-release from this and update virto to have this new updated release to test the tab panel background fix

**Comment by dmbarry86** [comment]
You should do the prerelease on this branch otherwise we have to go through the loop again if you find issues.

**Comment by dmbarry86** [comment]
@Skoob1905 I've created 8.1.1-1 pre-release for you. Please install and test it in VIRTO and report back here if it's all ok.

@lukemojo looks like somebody created 8.1.1-0 pre-release 10 days ago so I had to go up a number. I guess a mistake.

**Review by dmbarry86 — COMMENTED** [review]
Code change looks fine. Test the pre-release in VIRTO and if all is good then I'll approve.

**Comment by lukemojo** [comment]
> @Skoob1905 I've created 8.1.1-1 pre-release for you. Please install and test it in VIRTO and report back here if it's all ok.
> 
> @lukemojo looks like somebody created 8.1.1-0 pre-release tag 10 days ago so I had to go up a number. I guess a mistake.

@dmbarry86 Yes, mine. Turns out using pnpm version prerelease increments the patch number if doesn't already have a pre-release version

**Comment by Skoob1905** [comment]
Good news, aftering upgrading to new pre-release, we have our desired behaviour 
image

**Review by dmbarry86 — APPROVED** [review]

**Pull request merged**
