### PR TITLE
Feature/status labels

### PR DESCRIPTION
**Pull request by mattcorner**
- Added new **StatusLabel** component for use in TestCenter.
- Added new **StatusMessage** and **StatusIcon** components which are combined to make us StatusLabel. These are exposed as they may be required for future usage in TestCenter.

Figma designs:
As a label:
image
Icon only:
image

### CODE REVIEW

**Comment by dmbarry86** [comment]
I have some time so I will review this now.

**Comment by mattcorner** [comment]
> Code looks good. Just one question. How do the status icons look in dark mode?

Looks fine to me, was this a question or a hint that they don't?

I've opened up another PR that adds dark mode to storybook so we can test this kind of thing more easily.

**Comment by dmbarry86** [comment]
> Looks fine to me, was this a question or a hint that they don't?

Yes it was a question. Can you share screenshot of how they look?

**Comment by mattcorner** [comment]
> 

image
image
image
image
image
image
image

Just maybe the the "running" needs to be a bit brighter?

**Comment by dmbarry86** [comment]
> Just maybe the the "running" needs to be a bit brighter?

Looks OK I think. We can go with it.

**Pull request merged**
