### PR TITLE
Feature/rename app layout to virto app layout

### PR DESCRIPTION
**Pull request by jegasriskantha**
relates to https://github.com/orgs/IPG-Automotive-UK/projects/15

### Changes
This PR just renames AppLayout to VirtoAppLayout as a new new generic AppLayout without VIRTO branding will be created in an upcoming PR.

### Do Not Merge
requires changes in this PR https://github.com/IPG-Automotive-UK/react-ui/pull/585 to be merged first

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] Branch has been run in docker.
- [x] Assigned to me.
- [x] Relevant tags added.
- [x] Appropriate tests have been added.
- [x] Lint and test workflows pass.

### CODE REVIEW

**Comment by mattcorner** [comment]
@jegasriskantha Do we have any other breaking changes like this planned? It might be helpful to group them together in a major version bump because we'll have to touch every app to switch over the imports right?

**Comment by jegasriskantha** [comment]
> @jegasriskantha Do we have any other breaking changes like this planned? It might be helpful to group them together in a major version bump because we'll have to touch every app to switch over the imports right?

This is the last breaking change, but it would be nice to group this with the new app layout. PR will be opened this week.

**Comment by mattcorner** [comment]
> > @jegasriskantha Do we have any other breaking changes like this planned? It might be helpful to group them together in a major version bump because we'll have to touch every app to switch over the imports right?
> 
> This is the last breaking change, but it would be nice to group this with the new app layout. PR will be opened this week.

Shall we hold off merging until we're ready to go with all the PRs for the breaking release then?

**Comment by jegasriskantha** [comment]
> > > @jegasriskantha Do we have any other breaking changes like this planned? It might be helpful to group them together in a major version bump because we'll have to touch every app to switch over the imports right?
> > 
> > 
> > This is the last breaking change, but it would be nice to group this with the new app layout. PR will be opened this week.
> 
> Shall we hold off merging until we're ready to go with all the PRs for the breaking release then?

Yes sounds good to me, I'll manage this and notify everyone.

**Pull request merged**
