### PR TITLE
Bug/td 1556

### PR DESCRIPTION
**Pull request by m4manjesh**
Closes https://sce.myjetbrains.com/youtrack/issue/TD-1556/Sidebar-persists-when-switching-b-w-apps

Also;
- Reduced gap between VIRTO logo and App Name (https://github.com/IPG-Automotive-UK/test-center/pull/271#issuecomment-1465741683 )

Note: Once the react-ui is released, I will update all VIRTO apps.

### CODE REVIEW

**Comment by m4manjesh** [comment]
> @dmbarry86 I found an issue, fixing it. Will let you know once done.

It's good to go.

**Comment by dmbarry86** [comment]
@Sowbhagya-ipg this is the new spacing between VIRTO the dot and the app name. Are you happy with this?

image

**Review by dmbarry86 — APPROVED** [review]
Code changes look fine to me. Sowbhagya should confirm the spacing is now correct and then can be merged or updated accordingly.

**Comment by Sowbhagya-ipg** [comment]
This looks fine @dmbarry86 @m4manjesh

**Pull request merged**
