### PR TITLE
Password manager integration

### PR DESCRIPTION
**Pull request by dmbarry86**
Fixes issue with password manager not always recognising username field when registering a new account, changing password when logged in or resetting password. Fix was actually a simple one in the end and just required autocomplete on the email fields to be set to username. Have tested all password components using Chrome & Edge password managers and now username (email address in our case) is correctly picked up.

Closes https://github.com/IPG-Automotive-UK/react-ui/issues/98

### CODE REVIEW

**Comment by mattcorner** [comment]
Changes look good for the registration and login forms, tested in chrome. 

 I don't think it closes the linked issue which talks about the password change forms though. We discussed that they probably need a hidden username/email field

**Comment by dmbarry86** [comment]
> Changes look good for the registration and login forms, tested in chrome.
> 
> I don't think it closes the linked issue which talks about the password change forms though. We discussed that they probably need a hidden username/email field to allow the password manager to know which credentials are being modified and store them.

It certainly has fixed it for me. The password manager now correctly knows which user you are logged in as and when I change password it now correctly offers to update the already saved password for the currently logged in user. I assumed this was because the login form now correctly knows about username and password manager then makes the link when changing password. I tested changing password in both Chrome and Edge and it works fine. Is it not working for you?

**Comment by dmbarry86** [comment]
> Changes look good for the registration and login forms, tested in chrome.
> 
> I don't think it closes the linked issue which talks about the password change forms though. We discussed that they probably need a hidden username/email field to allow the password manager to know which credentials are being modified and store them. I guess maybe it works when there's only one account for a domain, but what if you have two accounts?

No it works fine for me with multiple accounts saved.

**Comment by dmbarry86** [comment]
> I guess maybe it works when there's only one account for a domain, but what if you have two accounts?

Works fine for me with multiple accounts

**Review by mattcorner — APPROVED** [review]
Yeah okay, the inbuilt password managers in Chrome and Edge seem to be a cleverer than LastPass in this regard. It seems they default to updating the last credentials used for a domain which makes sense, whereas LastPass clocks the credentials change, but asks me which of my accounts I want to update on this domain.

**Pull request merged**
