### PR TITLE
Model button component

### PR DESCRIPTION
**Pull request by dmbarry86**
Contributes to TD-1273.

Added a new model button component as per https://www.figma.com/file/B75H0DFTEiUFjJtehIKa8M/Model-Manager?node-id=1451%3A53435&t=WpgDwwhWuRpQtzje-1

image

Component accepts props for disabled, icon, label, onClick and status. Styled as per Figma. Border color is set based on the status prop (none, error, warning or success). Hover effect changes border and icon to blue. Supports dark and light mode.

There will be a separate PR for the ModelButtonGroup component which will accept this ModelButton as children.

### CODE REVIEW

**Comment by mattcorner** [comment]
Is the expectation that when the button is disabled, the coloured outline remains? This feels a little weird to me. Its not immediately distinguishable as disabled.

**Comment by dmbarry86** [comment]
> Is the expectation that when the button is disabled, the coloured outline remains? This feels a little weird to me. Its not immediately distinguishable as disabled.

I don't think there's a Figma for that case. Maybe @Sowbhagya-ipg can confirm whether disabled state should show grey or with the red/green/amber etc.

**Comment by Sowbhagya-ipg** [comment]
@dmbarry86  @mattcorner  Check the Icon Main Components Page in Figma. You can find the states and colours used for icons. Also you can find it for dark theme.

**Comment by mattcorner** [comment]
Some deviations from the Figma:

- [ ] Disabled state should also apply to the label and outline as well as the icon.
- [ ] Hover should apply a faded blue background
- [ ] Label font-size should be 13px.

**Review by mattcorner — CHANGES_REQUESTED** [review]
Just some styling stuff to resolve. Code and functionality looks good.

**Review by mattcorner — CHANGES_REQUESTED** [review]
Don't think the disabled font styling is being applied to label, other than that looks good.

**Review by mattcorner — APPROVED** [review]

**Pull request merged**
