### PR TITLE
Feature/summary cards

### PR DESCRIPTION
**Pull request by jegasriskantha**
closes https://sce.myjetbrains.com/youtrack/issue/TD-889/Create-new-Metadata-card-in-react-ui

### Summary: 
- Implements new detail card component to view detailed metadata and hero image
- Implements new file card component to search and download files 
- Implements new summary card component to view summary metadata and hero image

### Detail Card
image

### File Card
image

### Summary Card
image

### CODE REVIEW

**Comment by dmbarry86** [comment]
I think the image might look better left aligned rather than centered. All other items are left aligned (apart from edit/delete which are purposely on the right).

image

**Comment by dmbarry86** [comment]
Also seems a bit weird that the full screen view shows image with different aspect ratio to the compact view. @Sowbhagya-ipg

**Comment by dmbarry86** [comment]
Also seems like the detail card has fixed edit and delete buttons but compact view allows me to pass in my own options. What happens to my other options in full screen view? For example in VVB we have edit/delete/reconfigure. @Sowbhagya-ipg

**Comment by dmbarry86** [comment]
I wonder if it would look better with the first column having a width based on the contents (up to some max) so in this example here the second column would be shifted left to align with the heading column and then all of the white space would be on the right? @Sowbhagya-ipg 

image

**Comment by Sowbhagya-ipg** [comment]
> I wonder if it would look better with the first column having a width based on the contents (up to some max) so in this example here the second column would be shifted left to align with the heading column and then all of the white space would be on the right? @Sowbhagya-ipg
> 
> image

Yes, That might look nice. I will try that and see.

**Comment by Sowbhagya-ipg** [comment]
> Also seems like the detail card has fixed edit and delete buttons but compact view allows me to pass in my own options. What happens to my other options in full screen view? For example in VVB we have edit/delete/reconfigure. Maybe I should just be able to pass in these options in details view as well and if I want delete/edit/reconfigure I can pass. @Sowbhagya-ipg

The idea is to have all the possible buttons at the top. If it includes reconfigure, then yes we should have reconfigure button at the top

**Comment by Sowbhagya-ipg** [comment]
> Also seems a bit weird that the full screen view shows image with different aspect ratio to the compact view. @Sowbhagya-ipg

I thought of zooming in the image, but now i realise the images will pixelate if we zoom it that bigger. I will rethink the design for this full page view @dmbarry86

**Comment by dmbarry86** [comment]
@Sowbhagya-ipg and @jegasriskantha what's the latest with the design refinements? Are we sticking how they are now or are you planning to implement some updates based on above comments? I'll continue reviewing the code implementation once I get the green light from you.

**Comment by Sowbhagya-ipg** [comment]
@dmbarry86  I am working on the designs based on your feedback.

**Comment by jegasriskantha** [comment]
@dmbarry86 still some work to do here, I have removed you as reviewer to stop you getting spammed with updates.  Will add you again when it is ready for review

**Comment by dmbarry86** [comment]
@nikitharani the failing tests should be fixed before I start reviewing this.

**Comment by nikitharani** [comment]
ready to review. @dmbarry86

**Comment by dmbarry86** [comment]
It's probably a bit too late in the day now but for future referfence I think it's better to use component composition rather than exposing lots of different props for each possible customisable bit of the UI (content, buttonsStack etc). 

So we would follow something like Dialog in MUI or even Sidebar in this library.

Instead of:
```
<Card content={<div>Your Stuff </div>} buttonsStack={<div>Your Stuff </div>}>
```

Something like this
```
<Card>
   <CardContent>
      <div>Your Stuff</div>
   </CardContent>
   <CardActions>
      <div> Your Stuff </div>
   </CardActions>
</Card>
```

**Comment by dmbarry86** [comment]
You have stories for DetailCard, SummaryCard and TableCard

image


But the library actually exports DetailCard, SummaryCard and FileCard.

image

**Comment by dmbarry86** [comment]
Maybe I'm missing something but I don't see any action getting fired if I click on one of the file chips or the download all files button.

image

It looks like I pass an array of files rather than the UI elements themselves so I would expect some onClickFile, onClickDownloadAll etc to be exposed so use in each app.

**Comment by dmbarry86** [comment]
Cards look a bit different in dark and light mode.

In light mode all of the backgrounds are white.

image

In dark mode some backgrouns are black and some are grey.
image

Is this intended behaviour?

**Review by dmbarry86 — CHANGES_REQUESTED** [review]
- [ ] Evaluate effort to switch to component composition and feedback so we can make decision how to proceed.
- [x] Align library exports with stories.
- [x] Confirm dark/light mode is working as intended.
- [ ] Check file chip and file download button callbacks are exposed.

**Review by dmbarry86 — APPROVED** [review]
@nikitharani I'll leave you to deal with merging, updating release notes and making the release.

**Pull request merged**
