### PR TITLE
TD-2691 Create React UI Part Selector Component

### PR DESCRIPTION
**Pull request by syedsalehinipg**
Closes [TD-2691](https://sce.myjetbrains.com/youtrack/issue/TD-2691)

## Changes

This PR introduces a new component, `PartSelector` to the library. The `PartSelector` is a user interface component that allows users to select a part from a list of parts. It is designed to be flexible and reusable in different parts of the application.

### Features:

1. **Part Name Selection**: The component provides an autocomplete dropdown that lists all the unique part names. Users can select a part name from this dropdown.

2. **Part Number Selection**: Based on the selected part name, the component provides a second autocomplete dropdown that lists all the part numbers associated with the selected part name. This dropdown is disabled until a part name is selected.

3. **Flexible Layout**: The component can be displayed in a row or column layout, controlled by the `flexDirection` prop. It also controls the wrapping of items with the `flexWrap` prop.

4. **Controlled Component**: The `PartSelector` is a controlled component. It accepts a `value` prop that represents the currently selected part (both name and number), and an `onChange` callback that is called whenever the selection changes.

5. **Utility Function Integration**: The component uses a utility function `uniqueSortedArray` to sort and get unique part names.

_The initial use case for this component will be in VIRTO.DATA > Search > SELECT PART (tab)_

**Other changes:**

- Autocomplete.tsx
   -  New prop added for no options text, made us of `noOptionsText` prop of MuiAutocomplete

- utils/common.ts

  - Added `uniqueSortedArray` function (moved from VehicleSelector.tsx)

- VehicleSelector

    - New story added for custom size variant in `VehicleSelector.stories.tsx`
    - Use of the `uniqueSortedArray` from the utils/common function, removed `uniqueSortedArray` function from `VehicleSelector.tsx`
    - New `size` prop added in `VehicleSelector.types.ts` and implemented use of `size` in `VehicleSelector.tsx`

## UI/UX

_Initial light mode_
image

_Initial dark mode_
image

_Part Name selected_
image

_Filled
`size`: small
`flexDirection`: row_
image

## Testing notes

- Part Name Selection: 
    - Start by testing the part name selection. Click on the "Part Name" dropdown.
    - Select a part name from the list. The selected part name should be displayed in the "Part Name" field.

- Part Number Selection: 
    - Once a part name is selected, the "Part Number" dropdown should become enabled. 
    - Click on it and you should see a list of part numbers associated with the selected part name. 
    - Select a part number from the list. 
    - The selected part number should be displayed in the "Part Number" field.

- Layout: 
    - The component should be displayed in a column layout by default. If the `flexDirection` prop is set to "row", the component should be displayed in a row layout. 
    - The `flexWrap` prop controls whether the items should wrap onto multiple lines.

- Clearing Selection: 
    - Clear the selection in the "Part Name" field. 
    - The "Part Number" field should become disabled and its selection should be cleared as well.

- Size: 
    - The size of the component can be controlled by the size prop. 
    - Try changing the `size` prop to "small" or "medium" and observe the changes in the component's size.

- Unique Part Names: 
    - The "Part Name" dropdown should only display unique part names. 
    - If there are duplicate part names in the parts prop, they should only appear once in the dropdown.

- Sorting: 
    - The part names in the "Part Name" dropdown should be sorted in ascending order.

### PLEASE NOTE:

- After approval the component will be tested in VIRTO via pre-release.

- Failed end-to-end are a known issue.

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
~~- [ ] Branch has been run in docker.~~
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [x] Lint and test workflows pass.

### CODE REVIEW

**Review by AronPetrauskas — CHANGES_REQUESTED** [review]
I have left some comments within the code outlining issues I have found while testing. Here I will outline a couple more.

**Non-unique part numbers in drop down:**
Screenshot 2024-04-29 153516

**Part numbers are not sorted in any order it seems**
Screenshot 2024-04-29 153703

**`nowrap` seems to do nothing:**
noWrapNotWorking

**Comment by syedsalehinipg** [comment]
> I have left some comments within the code outlining issues I have found while testing. Here I will outline a couple more.
> 
> **`nowrap` seems to do nothing:** noWrapNotWorking

The `flexWrap` does take affect, if you have more fields:

image

image

**Comment by AronPetrauskas** [comment]
> > I have left some comments within the code outlining issues I have found while testing. Here I will outline a couple more.
> > **`nowrap` seems to do nothing:** noWrapNotWorking
> 
> The `flexWrap` does take affect, if you have more fields:
> 
> image
> 
> image

Apologies, I misunderstood the function of the `flexWrap` prop.

**Review by AronPetrauskas — APPROVED** [review]
All fixes implemented. LGTM!

**Pull request merged**
