### PR TITLE
Future/pnpm

### PR DESCRIPTION
**Pull request by mattcorner**
## Changes

Changes from using `npm` as a package manager to [`pnpm`](https://pnpm.io/).

Benefits:
- Code does not have access to dependencies of dependencies. The package.json must explicitly list all dependencies used in code.
- More disk efficient. Symlinks node_modules to a global store. 
- More performant. Keeps a global store so if a dependency already exists, it does not need to redownload.
- Github Action caching - Keep a global store for github actions.

More detail on Github Action Caching:
The cache key is `${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}`. 

> GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 10 GB. Once a repository has reached its maximum cache storage, the cache eviction policy will create space by deleting the oldest caches in the repository.

Hence as long as no pnpm-lock.yaml file have not changed, then we will hit the cache.

## Testing notes

All developers will need to install `pnpm`. There are many methods to doing so: https://pnpm.io/installation

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] ~Appropriate tests have been added.~
- [x] Lint and test workflows pass.

### CODE REVIEW

**Comment by dmbarry86** [comment]
@mattcorner would you like me to have a bash with this?

**Comment by mattcorner** [comment]
Couple more bits to wrap my head around, but i'll send it you way when ready.

**Comment by dmbarry86** [comment]
I assume these are dependencies of dependencies and not something we can control?

image

**Review by dmbarry86 — APPROVED** [review]
LGTM. Let's just have a quick chat tomorrow before merging to align on couple of things.

**Comment by mattcorner** [comment]
> I assume these are dependencies of dependencies and not something we can control?
> 
> image

Dependencies of plotly.js iirc.

**Comment by dmbarry86** [comment]
I think we're good to go with this now @mattcorner? I assume your prerelease worked as expected?

**Pull request merged**
