### PR TITLE
Create figure component

### PR DESCRIPTION
**Pull request by AronPetrauskas**
## Changes

Introduces a component 'Figure' to RUI. This is a component that is used to draw images on a konva canvas. Testing has been moved to a docker container. This is done as for image comparisons the CI tests are run on a linux machine. To replicate this locally a docker container for testing RUI was created. This can be run using `pnpm run test:docker`

- Figure component created
- Figure component variations created in storybook
- End to end unit test created in playwright.
- New CI workflow. MacOs and Windows tests removed.
- Docker environment created for testing code locally on Linux.

Currently the playwright tests in general seem flaky. In the future this needs to be addressed.

## Testing notes

1. Checkout the branch
2. `pnpm i`
3. `pnpm run storybook`
4. Test the 'Figure' component under Road View (category)
Test all props can be changed and the component updates as expected
5. Using the testing tab in VSCode run the tests manually. Make sure they all run. **_Make sure storybook is running before testing!_**
 **NOTE: You'll have to run the test at least twice.** First run generates the reference images. Make sure the reference images display the expected component.
image

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [x] Lint and ~~test workflows~~ pass. **IGNORE TEST FAILING DUE TO FLAKY PLAYWRIGHT**

### CODE REVIEW

**Comment by AronPetrauskas** [comment]
Ignore the flaky CI tests. Locally the components did pass the tests. The flaky tests on RUI are a known issue and shouldn't block the merging of the PR.

**Review by lukemojo — APPROVED** [review]
In the future it could be helpful to add a clearer note about the packages introduced  and why (konva, and use-image) just to help the reviewer along. I also would have preferred the docker test changes and the figure component changes separated into different PRs. Otherwise LGTM!

**Comment by AronPetrauskas** [comment]
> In the future it could be helpful to add a clearer note about the packages introduced and why (konva, and use-image) just to help the reviewer along. I also would have preferred the docker test changes and the figure component changes separated into different PRs. Otherwise LGTM!

Duly noted, good feedback. I will make sure to implement these suggestion in my future PRs. Apologies for any inconvenience.

**Comment by dmbarry86** [comment]
@AronPetrauskas @arpadlomenipg @lukemojo you raised a good point there which maybe you are not all familiar with as new starters. If we are introducing any new libraries then either @mattcorner or myself need to check them and approve them. This is a request from HQ to ensure we are not using any libraries which have weird licensing agreements etc which might prohibit the sale of any of our products that make use of them.

**Comment by dmbarry86** [comment]
FYI I think you forgot (and reviewer missed) to export the component from the root index file. You won't actually be able to import it in any app if you don't export it 😉

**Pull request merged**
