### PR TITLE
TDt-3190 Export FilterButton and ClearFilterButton separatily

### PR DESCRIPTION
**Pull request by m4manjesh**
Closes [TD-3190](https://sce.myjetbrains.com/youtrack/issue/TD-3190/Update-VIRTO-apps-with-new-SidebarFilter)

This PR is to seperates `FilterButton` and `ClearFilterButton` which was part of `SidebarFilter` to use individually in required cases.

## Changes

- Added `FilterButton` component with stories and tests
- Added `ClearFilterButton` component with stories and tests
- Integrated both components in `SidebarFilter`

## UI/UX

FilterButton
Screenshot 2024-11-13 120727

ClearFilterButton
Screenshot 2024-11-13 120711

In SidebarFilter
Screenshot 2024-11-13 120623

## Testing notes

- Check new `FilterButton` and `ClearFilterButton` components under `Filter` folder and works fine
- Check `SidebarFilter` with new components still works same as before

## Author checklist

Before I request a review:

- [x] I have reviewed my own code-diff.
- [x] I have tested the changes in Docker / a deploy-preview.
- [x] I have assigned the PR to myself or an appropriate delegate.
- [x] I have added the relevant labels to the PR.
- [x] I have included appropriate tests.
- [x] I have checked that the Lint and Test workflows pass on Github.
- [x] I have populated the deploy-preview with relevant test data.
- [x] I have tagged a UI/UX designer for review if this PR includes UI/UX changes.

### CODE REVIEW

**Comment by m4manjesh** [comment]
@Sowbhagya-ipg Can you please check the UI since there is a small change in clear button text from "CLEAR ALL FILTER" to "CLEAR ALL FILTERS"

**Comment by dmbarry86** [comment]
Can I suggest we rename FilterButton to SetFilterButton because now you have two buttons. You already called one CancelFilterButton but the other one just FilterButton which is now ambiguous.

**Comment by dmbarry86** [comment]
@m4manjesh I think this is also not what we spoke about. We spoke about exporting the SetFilterButton and a FilterStack. The FilterStack would handle the rendering of children, the scrolling and the clear button creation.

**Comment by m4manjesh** [comment]
> @m4manjesh I think this is also not what we spoke about. We spoke about exporting the SetFilterButton and a FilterStack too. The FilterStack would handle the rendering of children, the scrolling and the clear button creation fixed to the bottom. It's fine to also export the ClearFilterButton but in this case VIRTO.SCENE would use the SetFilterButton and the FilterStack components. The SideBarFilter would also use both of these components I think.

Renamed the FilterButton to SetFilterButton.

**Comment by dmbarry86** [comment]
> @dmbarry86 would you like to do a full review or shall i ask again in group chat?

Like is a strong word. I can do it though :-)

**Comment by m4manjesh** [comment]
@dmbarry86 I think i should do a pre-release for this first to test in the new PR first then will ask for review.

**Comment by Sowbhagya-ipg** [comment]
I tested in the storybook and so far it looks good. @m4manjesh

**Comment by dmbarry86** [comment]
> Like is a strong word. I can do it though :-)

Doesn't look like this is ready yet so you'll need to try and find somebody else to review it now as I'm on holiday tomorrow and finishing soon.

**Comment by m4manjesh** [comment]
[Link ](https://github.com/IPG-Automotive-UK/virto/pull/1160#issuecomment-2478691763) to test these changes in VIRTO

**Review by arpadlomenipg — APPROVED** [review]
LGTM. Full testing in the linked PR where it's applied to VIRTO apps is yet to be done though

**Pull request merged**
